version: '3'

services:
  api:
    build:
      context: mapsharingapi
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - mapsharingapi/.env
  dash:
    build:
      context: dash
      dockerfile: dash.Dockerfile
    ports:
      - "8050:8050"
    env_file:
      - dash/.env
    depends_on: 
      - api
    links:
      - api


